name: GCD Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up script permissions
      run: chmod +x kouyaku.sh test_kouyaku.sh

    - name: Run tests
      run: ./test_kouyaku.sh
